### ISSUE TITLE
Policy json format

### ISSUE THREAD

**Issue by CJendantix** [ading2210/policyedit#1]
The format for the policy json input for `patch` appears to be different than the output given by `view` (which isn't even valid vanilla JSON). What is the proper format?

**Comment by CJendantix** [comment]
I read through the code and got it to work! I'm going to fork the project and make some scripts and include improved documentation, expect a PR in a bit!

**Comment by ading2210** [comment]
The policy format is the same as what exporting the policies as JSON from `chrome://policy` would give you.

**Comment by ading2210** [comment]
It looks something like this:
```json
{
   "chromeMetadata": {
      "application": "Google Chrome",
      "platform": "14816.131.0 (Official Build) stable-channel kefka",
      "revision": "bcb0e65ad2f1e2bedb2d41e4cc15ec825ae3b7fd-refs/branch-heads/5060@{#1253}",
      "version": "103.0.5060.132 (Official Build) (64-bit)"
   },
   "chromePolicies": {
      "AdsSettingForIntrusiveAdsSites": {
         "level": "mandatory",
         "scope": "user",
         "source": "cloud",
         "value": 2
      },
      "AllowDeletingBrowserHistory": {
         "level": "mandatory",
         "scope": "user",
         "source": "cloud",
         "value": false
      },
      "AllowDinosaurEasterEgg": {
         "level": "mandatory",
         "scope": "user",
         "source": "sourceEnterpriseDefault",
         "value": false
      },
   }
}
```

**Comment by ading2210** [comment]
Of course, the only key that matters is `chromePolicies`, and everything else in the JSON file is ignored.

**Comment by CJendantix** [comment]
Ah, well those things weren't in any documentation and I didn't know you were trying to support that format. #2  changes the format quite a bit but retains the same key names. In my pull request it changes the output of `view` to the new format of `policies.json` so somebody trying to create a `policies.json` file could just run `main.py view --device-policy policy.1 > policies.json`
